### ISSUE TITLE
Add constructors for UnitVector

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djunits#9]
The construction of Vector and Matrix instances with units is cumbersome, and not intuitive. Currently, constructing involves code like:

```java
  double[] doubleValues = new double[] {0.2, 10.0, 5.7, 100.0, 15.0};
  DurationVector dva = DoubleVector.instantiate(doubleValues, DurationUnit.MINUTE, StorageType.DENSE);
```

More intuitive would be:

```java
  double[] doubleValues = new double[] {0.2, 10.0, 5.7, 100.0, 15.0};
  DurationVector dva = new DurationVector(doubleValues, DurationUnit.MINUTE);
```

The code could assume that the `StorageType` is `DENSE`, since we offer the data as an array. In case we would offer the data as a `Map`  of indices to values, the code could assume that the `StorageType` is `SPARSE`. This would create in total 20 constructors for each Vector (and a similar number for each Matrix).

**Comment by averbraeck** [comment]
One problem that can be immediately foreseen is that because of type erasure of generics, some of the constructors cannot be easily created: `List<Double>` has the same signature as, e.g., `List<Length>`. Similarly, `SortedMap<Integer, Double>` for sparse vectors has the same erasure signature as `SortedMap<Integer, Speed>`.  We have to think of a way to solve this. One way could be to check the first item and assume all other entries are of the same type. Note, however, that a `Scalar` extends `Number`, just like `Double`...

**Comment by averbraeck** [comment]
Code generation makes it very easy to create these constructors, so that is for sure not a barrier.

**Comment by WJSchakel** [comment]
Wouldn't instantiation methods using `Double` need a unit, where those using `Length` or `Speed` would not, circumventing type erasure?

`LengthVector.instantiate(SortedMap<Integer, Double>, LengthUnit.SI)`

`LengthVector.instantiate(SortedMap<Integer, Length>)`

As `Double` is a final class, this would be safe. Using `SortedMap<Integer, Number>` or `SortedMap<Integer, ? extends Number>` can lead to errors, e.g.:

```
SortedMap<Integer, Length> map = ...
LengthVector.instantiate(map, LengthUnit.FOOT)` // Length.si from doubleValue() interpreted as foot
```

**Comment by averbraeck** [comment]
I am making a reference implementation, where I can see quickly what works for the constructors and what not.

**Comment by averbraeck** [comment]
Combinations of arguments we could include and that make sense; example for an Area object:

- `DoubleVectorData, AreaUnit` - construct directly from a `DoubleVectorData` object with a `displayUnit`

- `double[], AreaUnit, StorageType` - construct from double array with a `displayUnit`
- `double[], AreaUnit` - construct from double array with a `displayUnit`; assume `DENSE` b/c of array
- `double[], StorageType` - construct from double array with SI unit for display
- `double[]` - construct from double array with with SI unit for display; assume `DENSE` b/c of array

- `Area[], AreaUnit, StorageType` - construct from an `Area` array with a `displayUnit`
- `Area[], AreaUnit` - construct from an `Area` array with a `displayUnit`; assume `DENSE` b/c of array
- `Area[], StorageType` - construct from an `Area` array with SI unit for display
- `Area[]` - construct from an `Area` array with with SI unit for display; assume `DENSE` b/c of array

- `List<Double>, AreaUnit, StorageType` - construct from Double list with a `displayUnit`
- `List<Double>, AreaUnit` - construct from Double list with a `displayUnit`; assume `DENSE` b/c of array
- `List<Double>, StorageType` - construct from Double list with SI unit for display
- `List<Double>` - construct from Double list with with SI unit for display; assume `DENSE` b/c of array
_Clashes with List<Area>_

- `List<Area>, AreaUnit, StorageType` - construct from an `Area` list with a `displayUnit`
- `List<Area>, AreaUnit` - construct from an `Area` array with a `displayUnit`; assume `DENSE` b/c of array
- `List<Area>, StorageType` - construct from an `Area` array with SI unit for display
- `List<Area>` - construct from an `Area` array with with SI unit for display; assume `DENSE` b/c of array
_Clashes with List<Double>_

- `SortedMap<Integer, Double>, AreaUnit, StorageType` - construct from sparse Double map with a `displayUnit`
- `SortedMap<Integer, Double>, AreaUnit` - construct from sparse Double map with a `displayUnit`; assume `SPARSE` b/c of map
- `SortedMap<Integer, Double>, StorageType` - construct from sparse Double map with SI unit for display
- `SortedMap<Integer, Double>` - construct from sparse Double map with with SI unit for display; assume `SPARSE` b/c of map
_Clashes with SortedMap<Integer, Area>_

- `SortedMap<Integer, Area>, AreaUnit, StorageType` - construct from sparse `Area` map with a `displayUnit`
- `SortedMap<Integer, Area>, AreaUnit` - construct from sparse `Area` map with a `displayUnit`; assume `SPARSE` b/c of map
- `SortedMap<Integer, Area>, StorageType` - construct from sparse `Area` map with SI unit for display
- `SortedMap<Integer, Area>` - construct from sparse `Area` map with with SI unit for display; assume `SPARSE` b/c of map
_Clashes with SortedMap<Integer, Double>_

I count 24 constructors that could make sense in total...

**Comment by averbraeck** [comment]
The clashes can be solved by using a `List<? extends Number>` and  `SortedMap<Integer, ? extends Number>`., since both `Scalar` and `Double` extend `Number`. In an `instantiate` method of `DoubleVectorData`, we would have to decide whether the list or map contains `Area` objects or just plain `Number` objects from which we can get the `doubleValue()`. 

This would reduce the number of constructors per `Vector` to 16... (which is not a problem because the code is generated).

**Comment by averbraeck** [comment]
A second disadvantage (or problem to solve) is that the `displayUnit` for a `List<Number>` or Map<Integer, Number>` indicates the **unit in which the values are provided**. In case of a `List<Scalar>` or Map<Integer, Scalar>`, the internal storage is already in SI units, and the `displayUnit` is literally only meant **for the display unit itself**. This means that the `doubleValue()` of the underlying `Number` has a different meaning, dependent on whether the List/Map contains numbers or scalars...

**Comment by averbraeck** [comment]
Probably the last problem can be solved by a constructor like:

```java
public AreaVector(final List<? extends Number> data, final AreaUnit displayUnit, final StorageType storageType)
{
  this(data.size() == 0 ? DoubleVectorData.instantiate(new double[] {}, IdentityScale.SCALE, storageType)
      : data.get(0) instanceof Area ? DoubleVectorData.instantiate(data, IdentityScale.SCALE, storageType)
      : DoubleVectorData.instantiate(data, displayUnit.getScale(), storageType),
  displayUnit);
}
```

**Comment by averbraeck** [comment]
Constructors for Vector and FloatVector created and tested -- 100% test coverage and looking good!

**Comment by averbraeck** [comment]
Test Coverage for `Vector` classes and `FloatVector` classes shows correct working of the classes and their constructors.
